apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ngninx-hpa
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2
  maxReplicas: 10
  #metric:
  #  name: http_requests
  #target:
  #  type: AverageValue
  #  averageValue: 100
  metrics:
  - Type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


