#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
#pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels:
    app: nginx-serv
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80